project:
  type: website

#웹사이트 맨 위쪽에 있는 제목이랑 아이콘링크 설정
website:
  title: "Hoyeon's Blog"
  comments : false
  google-analytics: "G-JE4129QJZV"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/hoyeon1234/sin-hoyeon/tree/main/posts
        
#웹사이트 스타일 설정      
format:
  html:
    theme: Simplex
    css: styles.css
    toc: true
    code-fold: false
    code-line-numbers: true
    code-copy: true