<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.280">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="신호연">
<meta name="dcterms.date" content="2023-01-07">

<title>HIHO - Finite Difference Method with np.gradient</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../">
<script src="../../../site_libs/quarto-html/quarto.js"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-JE4129QJZV"></script>

<script type="text/javascript">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-JE4129QJZV', { 'anonymize_ip': true});
</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="../../../styles.css">
</head>

<body class="nav-fixed fullcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../../../index.html">
    <span class="navbar-title">HIHO</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../../about.html">
 <span class="menu-text">About me</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/hoyeon1234/sin-hoyeon/tree/main/posts"><i class="bi bi-github" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Finite Difference Method with np.gradient</h1>
                                <div class="quarto-categories">
                <div class="quarto-category">numpy</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>신호연 </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">January 7, 2023</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">




<section id="gradient와-수치미분" class="level1">
<h1><span style="color:#00994c"> <strong>Gradient와 수치미분</strong></span></h1>
<p><span class="math inline">\({\bf x} =\begin{bmatrix}x_1&amp;x_2&amp;\dots&amp;x_m\end{bmatrix}^T\)</span>일 때, <span class="math inline">\(x\)</span>에 대한 다변수함수 <span class="math inline">\(f({\bf x})\)</span>의 gradient는 다음과 같다.</p>
<span class="math display">\[\begin{aligned}
&amp;\text{gradient of }f({\bf{x}}) = \frac{\partial f}{\partial {\bf x}} = \nabla f(\bf{x}) =
\begin{pmatrix}
\frac{\partial f}{\partial x_1} \\ \frac{\partial f}{\partial x_2} \\ \vdots \\ \frac{\partial }{\partial x_m}
\end{pmatrix}
\end{aligned}\]</span>
<p>함수가 가지는 모든 변수에 대해서 편미분 한 뒤 모아놓은 벡터라고 생각하면 된다. 함수의 수식을 알고 미분이 가능하면 우리는 해석적으로 미분해서(미분공식써서) 그레디언트를 구하고 각각의 어떤 point에서의 편미분계수들도 구할 수 있다. 그러나 우리가 주어진 데이터는 함수f의 함숫값들이 주어진다. 예를 들면 다음과 같다.</p>
<div class="cell" data-execution_count="1">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-2"><a href="#cb1-2"></a>f <span class="op">=</span> np.array([<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">4</span>,<span class="dv">7</span>,<span class="dv">11</span>,<span class="dv">17</span>],dtype <span class="op">=</span> <span class="bu">float</span>)</span>
<span id="cb1-3"><a href="#cb1-3"></a><span class="bu">print</span>(<span class="st">"f(x)"</span>)</span>
<span id="cb1-4"><a href="#cb1-4"></a><span class="bu">print</span>(f)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>f(x)
[ 1.  2.  4.  7. 11. 17.]</code></pre>
</div>
</div>
<p>위와 같은 함숫값들만 주어질때에는 원래의 함수를 알기는 불가능하다. 따라서 도함수를 통한 정확한 미분계수를 구하기가 불가능하므로 주어진 데이터로 <span class="math inline">\(\bf x\)</span>에서의 <span style="color:blue"><strong>미분계수의 값을 근사</strong></span>적으로 구할 수 있는데 이를 수치미분이라 한다.</p>
</section>
<section id="taylor-series" class="level1">
<h1><span style="color : #00994C"> <strong>Taylor Series</strong></span></h1>
<p>수치미분을 구하기 위해서는 먼저 테일러 급수가 나온다. 함수 <span class="math inline">\(f\)</span>가 a를 포함하는 구간에서 무한번 미분 가능할 때, <span class="math inline">\(x = a\)</span>에서 <span class="math inline">\(f(x)\)</span>의 테일러 급수 전개(근사)는 다음과 같다.<br> <span class="math display">\[f(x) = \sum_{n=0}^{\infty}\frac{f^{n}(a)}{n!}(x-a)^n = f(a) + \frac{f^{'}(a)}{1!}(x-a) + \frac{f^{''}(a)}{2!}(x-a)^2 + \dots \]</span> 테일러급수는 어떤 함수를 다항함수의 합으로 표현하며 한점a에서의 미분계수의 합으로 표현한다는 것에 의미가 있다. 다만 주의할 점은 <span class="math inline">\(a\)</span>의 위치와 다항식의 차수이다. <span class="math inline">\(a\)</span>가 <span class="math inline">\(x\)</span>근처에 가까울 수록 원래의 함수를 잘 근사하며 다항식의 차수 <span class="math inline">\(n\)</span>이 클수록 오차가 작아진다.</p>
</section>
<section id="수치미분" class="level1">
<h1><span style="color : #00994C"> <strong>수치미분</strong></span></h1>
<p>위에서 언급했듯이 수치미분은 주어진 데이터를 가지고 어떤 지점에서의 미분계수의 <span class="math inline">\(\bf x\)</span>에서의 <span style="color:blue"><strong>미분계수의 값을 근사적으로</strong></span>구하는 것이다. 각각의 방법으로 <span class="math inline">\(x_j\)</span>에서의 미분계수(기울기)의 근삿값을 구해보면 다음과 아래의 그림과 같다. 가장오른쪽에 중앙차분법(central divided difference approximation)에 의한 기울기가 실제기울기와 가장 비슷해보인다.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="./Finite dif.png" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">Finite Difference Method</figcaption><p></p>
</figure>
</div>
<p><a href="https://pythonnumericalmethods.berkeley.edu/notebooks/chapter20.02-Finite-Difference-Approximating-Derivatives.html">그림출처 - Finite Difference Method: https://pythonnumericalmethods.berkeley.edu/notebooks/chapter20.02-Finite-Difference-Approximating-Derivatives.html</a></p>
<p>유한차분법의 각각의 방법으로 도함수의 근사값을 유도하면 다음과 같다. (유도 : <a href="#sec-plot">Section&nbsp;5</a>)</p>
<p>전향차분근사 <span class="math display">\[\begin{align}
&amp;f'(x_i) \overset{\sim}{=} \frac{f(x_{i+1})-f(x_i)}{h}\\
&amp;O(h) = - \frac{hf^{''}(x_i)}{2!} - \frac{h^2f^{'''}(x_i)}{3!} - \dots\\
&amp;\text{where, } h = x_{i+1} - x_i \nonumber
\end{align}\]</span></p>
<p>여기서 <span class="math inline">\(O(h)\)</span>는 무한한항을 유한한항으로 근사시킬때 나타나는 절단오차라고 하며 h가 포함된 항이 가장 크게 기여하므로 <span class="math inline">\(O(h)\)</span>로 표기한다. 절단오차에서 h의 차수는 크면 클수록 좋다. <span class="math inline">\(p&lt;q\)</span>라 가정하고 같은 구간안에서 더 많은 데이터를 얻었다고 하면 <span class="math inline">\(h\)</span>가 작아지면 작아질수록 <span class="math inline">\(h^p\)</span>가 최고차항인 절단오차 <span class="math inline">\(O(h^p)\)</span> 보다는 <span class="math inline">\(h^q\)</span>가 최고차항인 <span class="math inline">\(O(h^q)\)</span>가 더 빨리 작아지기 때문이다. <br></p>
<p>(1)번식을 도함수<span class="math inline">\(f'(x_i)\)</span>의 (1차)전향차분근사라고 한다.<span class="math inline">\(x_i\)</span>의 도함수(미분계수)를 구하기 위해 <span class="math inline">\(x_{i+1}\)</span>을 사용했기에 전향 + 절단오차의 차수가 1인 <span class="math inline">\(O(h)\)</span>이기 떄문에 그렇다.</p>
<p>후향차분근사 <span class="math display">\[\begin{align}
&amp;f'(x_i) \overset{\sim}{=} \frac{f(x_{i})-f(x_{i-1})}{h}\\
&amp;O(h) = \frac{h}{2!}f^{''}(x_i) - \frac{h^2}{3!}f{'''}(x_i)+\dots \\
&amp;\text{where, } h = x_{i} - x_{i-1}, \nonumber
\end{align}\]</span></p>
<p>(1)번식을 도함수<span class="math inline">\(f'(x_i)\)</span>의 (1차)후향차분근사라고 한다.<span class="math inline">\(x_i\)</span>의 도함수(미분계수)를 구하기 위해 <span class="math inline">\(x_{i-1}\)</span>을 사용했기에 후향 + 절단오차의 차수가 1인 <span class="math inline">\(O(h)\)</span>이기 때문이다. 또한 후향차분근사의 절단오차는 전향차분근사와 마찬가지로 <span class="math inline">\(O(h)\)</span>로 서로 동일하다.</p>
<p>중앙차분근사<br> <span class="math display">\[\begin{align}
&amp;f'(x_i) \overset{\sim}{=} \frac{f(x_{i+1})-f(x_{i-1})}{2h}\\
&amp;O(h) = - \frac{h^2}{3!}f{'''}(x_i)+\dots \\
&amp;\text{where, } h = x_{i} - x_{i-1} = x_{i+1} - x_i\nonumber
\end{align}\]</span></p>
<p>(1)번식을 도함수<span class="math inline">\(f'(x_i)\)</span>의 (2차)중앙차분근사라고 한다.<span class="math inline">\(x_i\)</span>의 도함수(미분계수)를 구하기 위해 <span class="math inline">\(x_{i-1},x_{i+1}\)</span>을 사용했기에 중앙이라는 단어가 붙었고 절단오차의 차수가 2인 <span class="math inline">\(O(h^2)\)</span>이기 때문이다. 또한 (2차)중앙차분근사의 절단오차는 <span class="math inline">\(O(h^2)\)</span>으로 최고차항이 <span class="math inline">\(h\)</span>인 전향,후향차분근사와는 다르다. 이는 같은 데이터를 가졌다고 하더라도 중앙차분근사법으로 구한 도함수의 근삿값이 해석적으로 구한값과 가장 비슷하며 또한 같은구간에서 데이터를 더 많이 취득할수록 더 빠르게 정확한값가 가까워짐을 의미한다.</p>
</section>
<section id="np.gradient" class="level1">
<h1><span style="color:#00994c"> <strong>np.gradient?</strong></span></h1>
<p>넘파이의 그레디언트 함수는 배열의 끝값을 제외한 내부의 포인트에서는 2차중앙차분근사(second order accurate central differences)를 미분계수를 계산하고 가장끝값에 있는 포인트들에대해서는 1차 혹은 2차 one-side 차분(전향,후향차분)근사를 통해서 수치미분을 해주는 함수다.</p>
<section id="차원-배열의-경우" class="level2">
<h2 class="anchored" data-anchor-id="차원-배열의-경우"><strong>1차원 배열의 경우</strong></h2>
<section id="ex-dx-1" class="level3">
<h3 class="anchored" data-anchor-id="ex-dx-1"><strong>Ex) <span class="math inline">\(dx\)</span> = 1</strong></h3>
<p>넘파이 1차원 배열이 다음과 같이 주어져 있다고 하자.</p>
<div class="cell" data-execution_count="16">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1"></a><span class="im">from</span> IPython.display <span class="im">import</span> display, Markdown</span>
<span id="cb3-2"><a href="#cb3-2"></a>f <span class="op">=</span> np.array([<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">4</span>,<span class="dv">7</span>,<span class="dv">11</span>,<span class="dv">16</span>],dtype<span class="op">=</span><span class="bu">float</span>)</span>
<span id="cb3-3"><a href="#cb3-3"></a><span class="bu">print</span>(f)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[ 1.  2.  4.  7. 11. 16.]</code></pre>
</div>
</div>
<p><span style="color:blue">np.gradient함수는 1차원 배열의 내부에 있는 각각의 값들은 <span class="math inline">\(x\)</span>값이 거리가 <span class="math inline">\(dx\)</span>=1씩 변화할때마다의 함숫값<span class="math inline">\(f(x)\)</span>들로 이해</span>한다. 즉,다음과 같다.</p>
<div class="cell" data-execution_count="15">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1"></a><span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="bu">len</span>(f)):</span>
<span id="cb5-2"><a href="#cb5-2"></a>    display(Markdown(<span class="vs">rf'$x_</span><span class="sc">{</span>i<span class="op">+</span><span class="dv">1</span><span class="sc">}</span><span class="vs">$에서의 함숫값 $f(x_</span><span class="sc">{</span>i<span class="op">+</span><span class="dv">1</span><span class="sc">}</span><span class="vs">)$ = </span><span class="sc">{</span>f[i]<span class="sc">}</span><span class="vs">'</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><span class="math inline">\(x_1\)</span>에서의 함숫값 <span class="math inline">\(f(x_1)\)</span> = 1.0</p>
</div>
<div class="cell-output cell-output-display">
<p><span class="math inline">\(x_2\)</span>에서의 함숫값 <span class="math inline">\(f(x_2)\)</span> = 2.0</p>
</div>
<div class="cell-output cell-output-display">
<p><span class="math inline">\(x_3\)</span>에서의 함숫값 <span class="math inline">\(f(x_3)\)</span> = 4.0</p>
</div>
<div class="cell-output cell-output-display">
<p><span class="math inline">\(x_4\)</span>에서의 함숫값 <span class="math inline">\(f(x_4)\)</span> = 7.0</p>
</div>
<div class="cell-output cell-output-display">
<p><span class="math inline">\(x_5\)</span>에서의 함숫값 <span class="math inline">\(f(x_5)\)</span> = 11.0</p>
</div>
<div class="cell-output cell-output-display">
<p><span class="math inline">\(x_6\)</span>에서의 함숫값 <span class="math inline">\(f(x_6)\)</span> = 16.0</p>
</div>
</div>
위에서 넘파이의 그래디언트는 끝값을 제외한 내부의 요소에는 중앙차분근사 양끝값에 대해서는 후향차분 또는 전향차분을 사용한다고 언급했었다. 계산한,<span class="math inline">\(x_2,x_5\)</span>에서 미분계수의 2차중앙차분근사는 다음과 같다.<br>
<span class="math display">\[\begin{aligned}
&amp;f^{'}(x_2) \overset{\sim}{=} \frac{f(x_3)-f(x_1)}{2h} = \frac{4-1}{2} = 1.5 \\
&amp;f^{'}(x_5) \overset{\sim}{=} \frac{f(x_6)-f(x_4)}{2h} = \frac{16-7}{2} = 4.5 \\
&amp;\text{where, } h = x_3-x_2 = x_2-x_1 = 1
\end{aligned}\]</span>
1차원 배열의 가장 처음에 오는 값에 전향차분근사를 사용하고 가장 마지막에 오는 값에서는 후향차분근사를 사용한다.
<span class="math display">\[\begin{aligned}
&amp;f^{'}(x_1) = \frac{f(x_2) - f(x_1)}{h} = \frac{2-1}{1} = 1 \\
&amp;f^{'}(x_6) = \frac{f(x_6) - f(x_5)}{h} = \frac{16-11}{1} = 5
\end{aligned}\]</span>
<p>계산한 값과 실제로 일치하는지 확인.</p>
<div class="cell" data-execution_count="62">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1"></a>num_diff <span class="op">=</span> np.gradient(f)</span>
<span id="cb6-2"><a href="#cb6-2"></a><span class="bu">print</span>(<span class="st">"np.gradient의 출력값"</span>)</span>
<span id="cb6-3"><a href="#cb6-3"></a><span class="bu">print</span>(num_diff)</span>
<span id="cb6-4"><a href="#cb6-4"></a><span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="bu">len</span>(num_diff)):</span>
<span id="cb6-5"><a href="#cb6-5"></a>    display(Markdown(<span class="vs">rf'$x_</span><span class="sc">{</span>i<span class="op">+</span><span class="dv">1</span><span class="sc">}</span><span class="vs">$에서의 도함수의 근삿값 $\frac</span><span class="ch">{{</span><span class="vs">dy</span><span class="ch">}}{{</span><span class="vs">dx</span><span class="ch">}}</span><span class="vs">|_</span><span class="ch">{{</span><span class="vs">x = x_</span><span class="sc">{</span>i<span class="op">+</span><span class="dv">1</span><span class="sc">}</span><span class="ch">}}</span><span class="vs">$ ~= </span><span class="sc">{</span>num_diff[i]<span class="sc">}</span><span class="vs">'</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>np.gradient의 출력값
[1.  1.5 2.5 3.5 4.5 5. ]</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><span class="math inline">\(x_1\)</span>에서의 도함수의 근삿값 <span class="math inline">\(\frac{dy}{dx}|_{x = x_1}\)</span> ~= 1.0</p>
</div>
<div class="cell-output cell-output-display">
<p><span class="math inline">\(x_2\)</span>에서의 도함수의 근삿값 <span class="math inline">\(\frac{dy}{dx}|_{x = x_2}\)</span> ~= 1.5</p>
</div>
<div class="cell-output cell-output-display">
<p><span class="math inline">\(x_3\)</span>에서의 도함수의 근삿값 <span class="math inline">\(\frac{dy}{dx}|_{x = x_3}\)</span> ~= 2.5</p>
</div>
<div class="cell-output cell-output-display">
<p><span class="math inline">\(x_4\)</span>에서의 도함수의 근삿값 <span class="math inline">\(\frac{dy}{dx}|_{x = x_4}\)</span> ~= 3.5</p>
</div>
<div class="cell-output cell-output-display">
<p><span class="math inline">\(x_5\)</span>에서의 도함수의 근삿값 <span class="math inline">\(\frac{dy}{dx}|_{x = x_5}\)</span> ~= 4.5</p>
</div>
<div class="cell-output cell-output-display">
<p><span class="math inline">\(x_6\)</span>에서의 도함수의 근삿값 <span class="math inline">\(\frac{dy}{dx}|_{x = x_6}\)</span> ~= 5.0</p>
</div>
</div>
</section>
<section id="ex-dx-not-1-default가-아닐-경우" class="level3">
<h3 class="anchored" data-anchor-id="ex-dx-not-1-default가-아닐-경우"><strong>Ex) <span class="math inline">\(dx \not = 1\)</span> (default가 아닐 경우)</strong></h3>
거리<span class="math inline">\(dx=2\)</span>일때 계산한,<span class="math inline">\(x_2,x_5\)</span>에서 미분계수의 2차중앙차분근사는 다음과 같다.<br>
<span class="math display">\[\begin{aligned}
&amp;f^{'}(x_2) \overset{\sim}{=} \frac{f(x_3)-f(x_1)}{2h} = \frac{4-1}{4} = 0.75 \\
&amp;f^{'}(x_5) \overset{\sim}{=} \frac{f(x_6)-f(x_4)}{2h} = \frac{16-7}{4} = 2.25 \\
&amp;\text{where, } h = x_3-x_1 = x_6-x_4 = 2
\end{aligned}\]</span>
거리가 <span class="math inline">\(dx=2\)</span>일때 배열의 양 끝값에서 전향,후향차분근사를 통한 미분계수의 값은 다음과 같다.
<span class="math display">\[\begin{aligned}
&amp;f^{'}(x_1) = \frac{f(x_2) - f(x_1)}{h} = \frac{2-1}{2} = 0.5 \\
&amp;f^{'}(x_6) = \frac{f(x_6) - f(x_5)}{h} = \frac{16-11}{2} = 2.5
\end{aligned}\]</span>
<p>x값 사이의 거리<span class="math inline">\(dx\)</span>를 바꾸고 싶다면? =&gt; 두번째 인수에 스칼라 대입하면 된다.</p>
<div class="cell" data-execution_count="87">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1"></a>dx <span class="op">=</span> <span class="dv">2</span></span>
<span id="cb8-2"><a href="#cb8-2"></a>num_diff <span class="op">=</span> np.gradient(f,dx)</span>
<span id="cb8-3"><a href="#cb8-3"></a><span class="bu">print</span>(<span class="st">"np.gradient의 출력값"</span>)</span>
<span id="cb8-4"><a href="#cb8-4"></a><span class="bu">print</span>(num_diff)</span>
<span id="cb8-5"><a href="#cb8-5"></a><span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="bu">len</span>(num_diff)):</span>
<span id="cb8-6"><a href="#cb8-6"></a>    display(Markdown(<span class="vs">rf'$x_</span><span class="sc">{</span>i<span class="op">+</span><span class="dv">1</span><span class="sc">}</span><span class="vs">$에서의 도함수의 근삿값 $\frac</span><span class="ch">{{</span><span class="vs">dy</span><span class="ch">}}{{</span><span class="vs">dx</span><span class="ch">}}</span><span class="vs">|_</span><span class="ch">{{</span><span class="vs">x = x_</span><span class="sc">{</span>i<span class="op">+</span><span class="dv">1</span><span class="sc">}</span><span class="ch">}}</span><span class="vs">$ ~= </span><span class="sc">{</span>num_diff[i]<span class="sc">}</span><span class="vs">'</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>np.gradient의 출력값
[0.5  0.75 1.25 1.75 2.25 2.5 ]</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><span class="math inline">\(x_1\)</span>에서의 도함수의 근삿값 <span class="math inline">\(\frac{dy}{dx}|_{x = x_1}\)</span> ~= 0.5</p>
</div>
<div class="cell-output cell-output-display">
<p><span class="math inline">\(x_2\)</span>에서의 도함수의 근삿값 <span class="math inline">\(\frac{dy}{dx}|_{x = x_2}\)</span> ~= 0.75</p>
</div>
<div class="cell-output cell-output-display">
<p><span class="math inline">\(x_3\)</span>에서의 도함수의 근삿값 <span class="math inline">\(\frac{dy}{dx}|_{x = x_3}\)</span> ~= 1.25</p>
</div>
<div class="cell-output cell-output-display">
<p><span class="math inline">\(x_4\)</span>에서의 도함수의 근삿값 <span class="math inline">\(\frac{dy}{dx}|_{x = x_4}\)</span> ~= 1.75</p>
</div>
<div class="cell-output cell-output-display">
<p><span class="math inline">\(x_5\)</span>에서의 도함수의 근삿값 <span class="math inline">\(\frac{dy}{dx}|_{x = x_5}\)</span> ~= 2.25</p>
</div>
<div class="cell-output cell-output-display">
<p><span class="math inline">\(x_6\)</span>에서의 도함수의 근삿값 <span class="math inline">\(\frac{dy}{dx}|_{x = x_6}\)</span> ~= 2.5</p>
</div>
</div>
</section>
<section id="ex-x값의-좌표를-직접-정해주는-경우" class="level3">
<h3 class="anchored" data-anchor-id="ex-x값의-좌표를-직접-정해주는-경우"><strong>Ex) x값의 좌표를 직접 정해주는 경우</strong></h3>
<p>이전에는 각각의 인덱스간의 거리는 모두 동일하게 기본값 1이거나 다른값을 사용했다. 그러지 않고 <span class="math inline">\(x_1,x_2,\dots,x_6\)</span>의 좌표를 직접 지정해주는 것도 가능하다. 함수의 2번재 인수에 좌표를 직접 넣어주면 된다.<br></p>
<p>먼저 x값의 좌표를 다음과 같다고 해보자.</p>
<div class="cell" data-execution_count="77">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1"></a>x <span class="op">=</span> np.array([<span class="fl">0.</span>, <span class="fl">1.</span>, <span class="fl">1.5</span>, <span class="fl">3.5</span>, <span class="fl">4.</span>, <span class="fl">6.</span>], dtype<span class="op">=</span><span class="bu">float</span>)</span>
<span id="cb10-2"><a href="#cb10-2"></a>f <span class="op">=</span> np.array([<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">4</span>,<span class="dv">7</span>,<span class="dv">11</span>,<span class="dv">16</span>],dtype<span class="op">=</span><span class="bu">float</span>)</span>
<span id="cb10-3"><a href="#cb10-3"></a><span class="bu">print</span>(<span class="st">"각각의 좌표와 함숫값"</span>)</span>
<span id="cb10-4"><a href="#cb10-4"></a><span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="bu">len</span>(x)):</span>
<span id="cb10-5"><a href="#cb10-5"></a>    display(Markdown(<span class="vs">rf'$x_</span><span class="sc">{</span>i<span class="op">+</span><span class="dv">1</span><span class="sc">}</span><span class="vs">$ = </span><span class="sc">{</span>x[i]<span class="sc">}</span><span class="vs">, $f(x_</span><span class="sc">{</span>i<span class="op">+</span><span class="dv">1</span><span class="sc">}</span><span class="vs">)$ = </span><span class="sc">{</span>f[i]<span class="sc">}</span><span class="vs">'</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>각각의 좌표와 함숫값</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><span class="math inline">\(x_1\)</span> = 0.0, <span class="math inline">\(f(x_1)\)</span> = 1.0</p>
</div>
<div class="cell-output cell-output-display">
<p><span class="math inline">\(x_2\)</span> = 1.0, <span class="math inline">\(f(x_2)\)</span> = 2.0</p>
</div>
<div class="cell-output cell-output-display">
<p><span class="math inline">\(x_3\)</span> = 1.5, <span class="math inline">\(f(x_3)\)</span> = 4.0</p>
</div>
<div class="cell-output cell-output-display">
<p><span class="math inline">\(x_4\)</span> = 3.5, <span class="math inline">\(f(x_4)\)</span> = 7.0</p>
</div>
<div class="cell-output cell-output-display">
<p><span class="math inline">\(x_5\)</span> = 4.0, <span class="math inline">\(f(x_5)\)</span> = 11.0</p>
</div>
<div class="cell-output cell-output-display">
<p><span class="math inline">\(x_6\)</span> = 6.0, <span class="math inline">\(f(x_6)\)</span> = 16.0</p>
</div>
</div>
<p>각각의 좌표에서 도함수의 근삿값을 구하면 아래와 같다.(수식 계산은 잘 모르겠네요 … 추후에 더 공부하겠습니다!)</p>
<div class="cell" data-execution_count="78">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1"></a>num_diff <span class="op">=</span> np.gradient(f,x)</span>
<span id="cb12-2"><a href="#cb12-2"></a><span class="bu">print</span>(<span class="st">"np.gradient의 출력값"</span>)</span>
<span id="cb12-3"><a href="#cb12-3"></a><span class="bu">print</span>(num_diff)</span>
<span id="cb12-4"><a href="#cb12-4"></a><span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="bu">len</span>(num_diff)):</span>
<span id="cb12-5"><a href="#cb12-5"></a>    display(Markdown(<span class="vs">rf'$x_</span><span class="sc">{</span>i<span class="op">+</span><span class="dv">1</span><span class="sc">}</span><span class="vs">$에서의 도함수의 근삿값 $\frac</span><span class="ch">{{</span><span class="vs">dy</span><span class="ch">}}{{</span><span class="vs">dx</span><span class="ch">}}</span><span class="vs">|_</span><span class="ch">{{</span><span class="vs">x = x_</span><span class="sc">{</span>i<span class="op">+</span><span class="dv">1</span><span class="sc">}</span><span class="ch">}}</span><span class="vs">$ ~= </span><span class="sc">{</span>num_diff[i]<span class="sc">}</span><span class="vs">'</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>np.gradient의 출력값
[1.  3.  3.5 6.7 6.9 2.5]</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><span class="math inline">\(x_1\)</span>에서의 도함수의 근삿값 <span class="math inline">\(\frac{dy}{dx}|_{x = x_1}\)</span> ~= 1.0</p>
</div>
<div class="cell-output cell-output-display">
<p><span class="math inline">\(x_2\)</span>에서의 도함수의 근삿값 <span class="math inline">\(\frac{dy}{dx}|_{x = x_2}\)</span> ~= 2.9999999999999996</p>
</div>
<div class="cell-output cell-output-display">
<p><span class="math inline">\(x_3\)</span>에서의 도함수의 근삿값 <span class="math inline">\(\frac{dy}{dx}|_{x = x_3}\)</span> ~= 3.5</p>
</div>
<div class="cell-output cell-output-display">
<p><span class="math inline">\(x_4\)</span>에서의 도함수의 근삿값 <span class="math inline">\(\frac{dy}{dx}|_{x = x_4}\)</span> ~= 6.700000000000001</p>
</div>
<div class="cell-output cell-output-display">
<p><span class="math inline">\(x_5\)</span>에서의 도함수의 근삿값 <span class="math inline">\(\frac{dy}{dx}|_{x = x_5}\)</span> ~= 6.899999999999999</p>
</div>
<div class="cell-output cell-output-display">
<p><span class="math inline">\(x_6\)</span>에서의 도함수의 근삿값 <span class="math inline">\(\frac{dy}{dx}|_{x = x_6}\)</span> ~= 2.5</p>
</div>
</div>
</section>
</section>
<section id="차원-배열의-경우-1" class="level2">
<h2 class="anchored" data-anchor-id="차원-배열의-경우-1"><strong>2차원 배열의 경우</strong></h2>
<p>2차원 배열의 경우 axis=0(세로축)과 axis=1(가로축) 두 축방향으로 계산한 도함수의 근삿값을 반환한다.axis=0일 경우 각각의 열마다 따로따로 독립적으로 <span class="math inline">\(x_1,x_2...\)</span>에 대한 함숫값<span class="math inline">\(f(x_1),f(x_2),\dots\)</span>이 있다고 생각하면 되고 axis=1일 경우 각각의 행마다 따로따로 독립적으로 <span class="math inline">\(x_1,x_2...\)</span>에 대한 함숫값<span class="math inline">\(f(x_1),f(x_2),\dots\)</span>이 있다고 생각하면 된다.또한 1차원 배열과 유사하게 각각의 행,열의 끝값에는 전향or후향차분근사를 행,열의 내부에 있는 값은 중앙차분근사를 사용한다.</p>
<section id="ex-dx1dy1" class="level3">
<h3 class="anchored" data-anchor-id="ex-dx1dy1"><strong>Ex) <span class="math inline">\(dx=1,dy=1\)</span></strong></h3>
<p>2차원 배열은 다음과 같다.</p>
<div class="cell" data-execution_count="92">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1"></a>np.array([[<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">6</span>], [<span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">5</span>]], dtype<span class="op">=</span><span class="bu">float</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="92">
<pre><code>array([[1., 2., 6.],
       [3., 4., 5.]])</code></pre>
</div>
</div>
<div class="cell" data-execution_count="90">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1"></a>ax0_difcoef,ax1_difcoef<span class="op">=</span> np.gradient(np.array([[<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">6</span>], [<span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">5</span>]], dtype<span class="op">=</span><span class="bu">float</span>))</span>
<span id="cb16-2"><a href="#cb16-2"></a><span class="bu">print</span>(<span class="ss">f'axis = 0 방향으로 도함수의 근삿값 계산 </span><span class="ch">\n</span><span class="sc">{</span>ax0_difcoef<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb16-3"><a href="#cb16-3"></a><span class="bu">print</span>(<span class="ss">f'axis = 1 방향으로 도함수의 근삿값 계산 </span><span class="ch">\n</span><span class="sc">{</span>ax1_difcoef<span class="sc">}</span><span class="ss">'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>axis = 0 방향으로 도함수의 근삿값 계산 
[[ 2.  2. -1.]
 [ 2.  2. -1.]]
axis = 1 방향으로 도함수의 근삿값 계산 
[[1.  2.5 4. ]
 [1.  1.  1. ]]</code></pre>
</div>
</div>
</section>
<section id="ex-dx-not-1dy-not-1-default가-아닌-경우" class="level3">
<h3 class="anchored" data-anchor-id="ex-dx-not-1dy-not-1-default가-아닌-경우"><strong>Ex) <span class="math inline">\(dx \not = 1,dy \not = 1\)</span> (default가 아닌 경우)</strong></h3>
<p>각각의 행,열마다 거리를 따로 설정해주고 싶은 경우? =&gt; 스칼라 2개 인수로 전달.</p>
<div class="cell" data-execution_count="91">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1"></a>dx <span class="op">=</span> <span class="dv">2</span><span class="op">;</span>dy <span class="op">=</span> <span class="dv">2</span></span>
<span id="cb18-2"><a href="#cb18-2"></a>ax0_difcoef,ax1_difcoef<span class="op">=</span> np.gradient(np.array([[<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">6</span>], [<span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">5</span>]], dtype<span class="op">=</span><span class="bu">float</span>),dx,dy)</span>
<span id="cb18-3"><a href="#cb18-3"></a><span class="bu">print</span>(<span class="ss">f'axis = 0 방향으로 도함수의 근삿값 계산 </span><span class="ch">\n</span><span class="sc">{</span>ax0_difcoef<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb18-4"><a href="#cb18-4"></a><span class="bu">print</span>(<span class="ss">f'axis = 1 방향으로 도함수의 근삿값 계산 </span><span class="ch">\n</span><span class="sc">{</span>ax1_difcoef<span class="sc">}</span><span class="ss">'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>axis = 0 방향으로 도함수의 근삿값 계산 
[[ 1.   1.  -0.5]
 [ 1.   1.  -0.5]]
axis = 1 방향으로 도함수의 근삿값 계산 
[[0.5  1.25 2.  ]
 [0.5  0.5  0.5 ]]</code></pre>
</div>
</div>
</section>
</section>
</section>
<section id="sec-plot" class="level1">
<h1><span style="color : #00994c"><strong>Appendix</strong></span></h1>
<section id="전향차분근사-유도" class="level2">
<h2 class="anchored" data-anchor-id="전향차분근사-유도"><strong>전향차분근사 유도</strong></h2>
<p><span class="math inline">\(x_1,x_2,\dots,x_{i-1},x_i,x_{i+1},\dots,x_n\)</span>과 각각에 대응하는 함숫값 <span class="math inline">\(f(x_1),f(x_2),\dots,f(x_{i-1}),f(x_i),f(x_{i+1}),\dots,f(x_n)\)</span> 주어진 데이터라고 가정하자. 목적은 x_i에서의 미분계수를 구하는 것이다. <span class="math inline">\(a = x_i\)</span>에서 함수<span class="math inline">\(f(x)\)</span>의 테일러 급수 근사는 다음과 같다.<br> <span class="math display">\[f(x) = \sum_{n=0}^{\infty}\frac{f^{n}(x_i)}{n!}(x-x_i)^n = f(x_i) + \frac{f^{'}(x_i)}{1!}(x-x_i) + \frac{f^{''}(x_i)}{2!}(x-x_i)^2 + \dots \]</span></p>
<p><span class="math inline">\(x=x_{i+1}\)</span>에서의 함숫값은 다음과 같다.<br> <span class="math display">\[f(x_{i+1}) = \sum_{n=0}^{\infty}\frac{f^{n}(x_i)}{n!}(x_{i+1}-x_i)^n = f(x_i) + \frac{f^{'}(x_i)}{1!}(x_{i+1}-x_i) + \frac{f^{''}(x_i)}{2!}(x_{i+1}-x_i)^2 + \dots \]</span></p>
<p><span class="math inline">\(f'(x_i)\)</span>가 포함된항만 남겨두고 나머지는 이항하면 다음과 같다.<br> <span class="math display">\[f^{'}(x_i)(x_{i+1}-x_i) = f(x_{i+1}) - f(x_i) - \frac{f^{''}(x_i)}{2!}(x_{i+1}-x_i)^2 + \dots\]</span></p>
<p><span class="math inline">\(h = x_{i+1}-x_i\)</span>로 두고 양변을 h로 나누면 다음과 같다.<br> <span class="math display">\[f'(x_i) = \frac{f(x_{i+1})}{h} - \frac{f(x_i)}{h} - \frac{hf^{''}(x_i)}{2!} - \frac{h^2f^{'''}(x_i)}{3!}\]</span></p>
<p>여기서 우변의 두개의 항만 남겨두고 <span class="math inline">\(O(h) = - \frac{hf^{''}(x_i)}{2!} - \frac{h^2f^{'''}(x_i)}{3!} - \dots\)</span>라 하면 다음과 같다.<br> <span class="math display">\[\begin{align}
&amp;f'(x_i) \overset{\sim}{=} \frac{f(x_{i+1})-f(x_i)}{h}\\
&amp;O(h) = - \frac{hf^{''}(x_i)}{2!} - \frac{h^2f^{'''}(x_i)}{3!} - \dots\\
&amp;\text{where, } h = x_{i+1} - x_i \nonumber
\end{align}\]</span></p>
</section>
<section id="후향차분근사-유도" class="level2">
<h2 class="anchored" data-anchor-id="후향차분근사-유도"><strong>후향차분근사 유도</strong></h2>
<p><span class="math inline">\(x_1,x_2,\dots,x_{i-1},x_i,x_{i+1},\dots,x_n\)</span>과 각각에 대응하는 함숫값 <span class="math inline">\(f(x_1),f(x_2),\dots,f(x_{i-1}),f(x_i),f(x_{i+1}),\dots,f(x_n)\)</span> 주어진 데이터라고 가정하자. 목적은 x_i에서의 미분계수를 구하는 것이다. <span class="math inline">\(a = x_i\)</span>에서 함수<span class="math inline">\(f(x)\)</span>의 테일러 급수 근사는 다음과 같다.<br> <span class="math display">\[f(x) = \sum_{n=0}^{\infty}\frac{f^{n}(x_i)}{n!}(x-x_i)^n = f(x_i) + \frac{f^{'}(x_i)}{1!}(x-x_i) + \frac{f^{''}(x_i)}{2!}(x-x_i)^2 + \dots \]</span></p>
<p><span class="math inline">\(f(x_i)\)</span>는 다음과 같다.<br> <span class="math display">\[f(x_{i-1}) = \sum_{n=0}^{\infty}\frac{f^n(x_i)}{n!}(x_{i-1}-x_i)^n = f(x_i) + \frac{f^{'}(x_i)}{1!}(x_{i-1}-x_i) + \frac{f^{''}(x_i)}{2!}(x_{i-1}-x_i)^2+\dots \]</span></p>
<p>1차미분이 포함된 항만 남기고 나머지는 이항하면 다음과 같다.<br> <span class="math display">\[f^{'}(x_i)(x_{i-1}-x_i) = f(x_{i-1}) - f(x_i) - \frac{f^{''}(x_i)}{2!}(x_{i-1}-x_i)^2-\frac{f^{'''}(x_i)}{3!}(x_{i-1}-x_i)^3-\dots \]</span></p>
<p><span class="math inline">\(h = x_{i} - x_{i-1}\)</span>로 놓으면 다음과 같다.<br> <span class="math display">\[f^{'}(x_i)(-h) = f(x_{i-1}) - f(x_i) - \frac{f^{''}(x_i)}{2!}h^2+\frac{f^{'''}(x_i)}{3!}h^3-\dots \]</span></p>
양변을 <span class="math inline">\(-h\)</span>로 나누면 다음과 같다.<br>
<span class="math display">\[\begin{aligned}
f^{'}(x_i) &amp;= \frac{f(x_{i-1})}{-h} + \frac{f(x_i)}{h} + \frac{f^{''}(x_i)}{2!}h-\frac{f^{'''}(x_i)}{3!}h^2+\dots \\
&amp;=\frac{f(x_i)-f(x_{i-1}) }{h} +  \frac{f^{''}(x_i)}{2!}h-\frac{f^{'''}(x_i)}{3!}h^2+\dots
\end{aligned}\]</span>
<p>마찬가지로 우변의 두개 항만 남겨두고 <span class="math inline">\(O(h) = \frac{hf^{''}(x_i)}{2!} - \frac{h^2f^{'''}(x_i)}{3!} + \dots\)</span>라 하면 다음과 같다. <span class="math display">\[\begin{align}
&amp;f'(x_i) \overset{\sim}{=} \frac{f(x_{i})-f(x_{i-1})}{h}\\
&amp;O(h) = \frac{h}{2!}f^{''}(x_i) - \frac{h^2}{3!}f{'''}(x_i)+\dots \\
&amp;\text{where, } h = x_{i} - x_{i-1}, \nonumber
\end{align}\]</span></p>
</section>
<section id="중앙차분근사-유도" class="level2">
<h2 class="anchored" data-anchor-id="중앙차분근사-유도"><strong>중앙차분근사 유도</strong></h2>
<p>전향차분근사와 후향차분근사의 유도과정에서의 테일러 전개식은 다음과 같다.<br> <span class="math display">\[f'(x_i) = \frac{f(x_{i+1})}{h} - \frac{f(x_i)}{h} - \frac{hf^{''}(x_i)}{2!} - \frac{h^2f^{'''}(x_i)}{3!} - ...\]</span> <span class="math display">\[f'(x_i) = \frac{f(x_{i})}{h} - \frac{f(x_{i-1})}{h} + \frac{hf^{''}(x_i)}{2!} - \frac{h^2f^{'''}(x_i)}{3!} + ...\]</span></p>
두 식을 더해주면 다음과 같다.
<span class="math display">\[\begin{aligned}
&amp;2f^{'}(x_i) = \frac{f(x_{i+1})-f(x_{i-1})}{h} - \frac{2h^2f^{'''}(x_i)}{3!} \\
&amp;\Leftrightarrow f^{'}(x_i) = \frac{f(x_{i+1})-f(x_{i-1})}{2h} - \frac{h^2f^{'''}(x_i)}{3!} - ...
\end{aligned}\]</span>
<p>마찬가지로 우변의 두개 항만 남겨두고 절단오차<span class="math inline">\(O(h^2) = -\frac{h^2f^{'''}(x_i)}{3!} - \dots\)</span>라 하면 다음과 같다. <span class="math display">\[\begin{align}
&amp;f'(x_i) \overset{\sim}{=} \frac{f(x_{i+1})-f(x_{i-1})}{2h}\\
&amp;O(h) = - \frac{h^2}{3!}f{'''}(x_i)+\dots \\
&amp;\text{where, } h = x_{i} - x_{i-1}\,\,\text{or}\,\, h = x_{i+1} - x_i\nonumber
\end{align}\]</span></p>
</section>
</section>
<section id="참고자료" class="level1">
<h1><span style="color : #00994C"><strong>참고자료</strong></span></h1>
<p><a href="https://darkpgmr.tistory.com/59">다크프로그래머 - 테일러급수의 이해와 활용</a><br> <a href="https://ko.wikipedia.org/wiki/%ED%85%8C%EC%9D%BC%EB%9F%AC_%EA%B8%89%EC%88%98">위키피디아 - 테일러급수</a><br> <a href="https://subprofessor.tistory.com/13">링크</a><br> <a href="https://m.blog.naver.com/PostView.naver?isHttpsRedirect=true&amp;blogId=y244&amp;logNo=221067641890">링크2</a><br> <a href="https://normal-engineer.tistory.com/97">링크3</a><br> <a href="http://www.ktword.co.kr/test/view/view.php?m_temp1=5885">링크4</a><br> <a href="https://pythonnumericalmethods.berkeley.edu/notebooks/chapter15.03-The-QR-Method.html">링크5</a></p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<script src="https://utteranc.es/client.js" repo="hoyeon1234/sin-hoyeon" issue-term="pathname" theme="github-light" crossorigin="anonymous" async="">
</script>
</div> <!-- /content -->



</body></html>